image_extensions = ['jpeg', 'jpg', 'png']
FAST_RUN = False
IMAGE_WIDTH = 128
IMAGE_HEIGHT = 128
IMAGE_SIZE = (IMAGE_WIDTH, IMAGE_HEIGHT)
IMAGE_CHANNELS = 3
SIZE = 128
DATA_DIR = "data/motif-sasirangan"
AUG_DATA_DIR = "data/augmented-data"
EVAL_DATA_PATH = "data/evaluation/data-evaluation.npy"
HIST_MODEL_PATH = "data/evaluation/model-history.npy"